-- Create database
CREATE DATABASE WEATHER_DATA;

-- Create raw schema
CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;
CREATE SCHEMA INTERMEDIATE;
CREATE SCHEMA MART;

-- Create raw tables
CREATE TABLE OPENWEATHER_RAW (
    ID NUMBER AUTOINCREMENT,
    city_Name STRING,
    latitude FLOAT,
    longitude FLOAT,
    PAYLOAD VARIANT NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE OPENMETEO_RAW (
    ID NUMBER AUTOINCREMENT,
    city_Name STRING,
    latitude FLOAT,
    longitude FLOAT,
    PAYLOAD VARIANT NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE WEATHERAPI_RAW (
    ID NUMBER AUTOINCREMENT,
    city_Name STRING,
    latitude FLOAT,
    longitude FLOAT,
    PAYLOAD VARIANT NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);