-- Create database
CREATE DATABASE WEATHER_DATA;

-- Create raw schema
CREATE SCHEMA RAW;

-- Create raw tables
CREATE TABLE OPENWEATHER_RAW (
    ID NUMBER AUTOINCREMENT,
    PAYLOAD VARIANT NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE OPENMETEO_RAW (
    ID NUMBER AUTOINCREMENT,
    PAYLOAD VARIANT NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE WEATHERAPI_RAW (
    ID NUMBER AUTOINCREMENT,
    PAYLOAD VARIANT NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);